# Generated by Django 2.1.11 on 2019-09-03 12:48

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfileInstructionsPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_profile_instructions', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile_instructions', slotname='seller_profile_instructions', to='cms.Placeholder')),
            ],
        ),
    ]
