# Generated by Django 2.1.11 on 2019-08-31 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_bannerconfig', serialize=False, to='cms.CMSPlugin')),
                ('width', models.CharField(choices=[('full-width', 'Full-Width No Side Margins'), ('container-fluid', 'Full-Width Small Side Margin'), ('container', 'Full-Width Wide Side Margin'), ('col-sm', 'Responsive Column')], default='full-width', max_length=255, verbose_name='Width')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Banner Plugins',
                'db_table': 'banner_plugin',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
