# Generated by Django 2.1.11 on 2019-09-01 01:00

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_plugins', '0002_bannerconfig_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerconfig',
            name='banner_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='banner_content', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='bannerconfig',
            name='width',
            field=models.CharField(choices=[('full-width', 'Full-Width No Side Margins'), ('container-fluid', 'Full-Width Small Side Margin'), ('container', 'Full-Width Wide Side Margin'), ('wide-centered', 'Wide Centered'), ('col-sm', 'Responsive Column')], default='full-width', max_length=255, verbose_name='Width'),
        ),
    ]
