# Generated by Django 2.1.11 on 2019-09-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0003_auto_20190831_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerconfig',
            name='banner_content_placement',
            field=models.CharField(choices=[('text-left-top', 'Left Top'), ('text-center', 'Center'), ('text-left-bottom', 'Left Bottom')], default='full-width', max_length=255, verbose_name='Banner Content Placement'),
        ),
    ]
