# Generated by Django 2.1.11 on 2019-09-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0005_remove_bannerconfig_banner_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerconfig',
            name='banner_content_placement',
        ),
    ]
