# Generated by Django 2.1.11 on 2019-09-15 21:36

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filer', '0011_auto_20190418_0137'),
        ('cms_plugins', '0007_auto_20190902_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightSliderConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_lightsliderconfig', serialize=False, to='cms.CMSPlugin')),
                ('gallery_folder', filer.fields.folder.FilerFolderField(on_delete=django.db.models.deletion.CASCADE, to='filer.Folder', verbose_name='Folder')),
            ],
            options={
                'verbose_name_plural': 'Light Slider Plugins',
                'db_table': 'light_slider_plugin',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
